INSERT INTO [Product].[AccommodationRoomType] ([Name], [IsDeleted])
VALUES
    (N'Single Room', 0),
    (N'Twin Room', 0),
    (N'Triple Room', 0),
    (N'Dormitory Six', 0),
    (N'Quad Room', 0),
    (N'Deluxe Single Room', 0),
    (N'Residence', 0),
    (N'Studio Single', 0),
    (N'Studio Twin', 0),
    (N'Studio Double', 0),
    (N'Dormitory Eight', 0),
    (N'Single Room Plus', 0),
    (N'Junior Suite', 0),
    (N'Double Room', 0),
    (N'Semi-Private Room', 0),
    (N'Single 1-2/Man/Downtown Room', 0),
    (N'Single 1-2 / Man Room', 0),
    (N'Twin 1-2 / Man Room', 0),
    (N'Twin 1-2/Man/Downtown Room', 0),
    (N'Dormitory Five', 0),
    (N'Deluxe Twin Room', 0),
    (N'Deluxe Double Room', 0),
    (N'Single Room Balcony', 0),
    (N'Economy Single', 0),
    (N'One Bedroom', 0)