INSERT INTO [ReferenceData].[Country] ([Code], [Name], [IsDeleted])
VALUES
    (N'AC', N'Ascension Island', 0),
    (N'AD', N'Andorra', 0),
    (N'AE', N'United Arab Emirates', 0),
    (N'AF', N'Afghanistan', 0),
    (N'AG', N'Antigua & Barbuda', 0),
    (N'AI', N'Anguilla', 0),
    (N'AL', N'Albania', 0),
    (N'AM', N'Armenia', 0),
    (N'AN', N'Netherlands Antilles', 0),
    (N'AO', N'Angola', 0),
    (N'AQ', N'Antarctica', 0),
    (N'AR', N'Argentina', 0),
    (N'AS', N'American Samoa', 0),
    (N'AT', N'Austria', 0),
    (N'AU', N'Australia', 0),
    (N'AW', N'Aruba', 0),
    (N'AX', N'Åland Islands', 0),
    (N'AZ', N'Azerbaijan', 0),
    (N'BA', N'Bosnia & Herzegovina', 0),
    (N'BB', N'Barbados', 0),
    (N'BD', N'Bangladesh', 0),
    (N'BE', N'Belgium', 0),
    (N'BF', N'Burkina Faso', 0),
    (N'BG', N'Bulgaria', 0),
    (N'BH', N'Bahrain', 0),
    (N'BI', N'Burundi', 0),
    (N'BJ', N'Benin', 0),
    (N'BL', N'St. Barthélemy', 0),
    (N'BM', N'Bermuda', 0),
    (N'BN', N'Brunei', 0),
    (N'BO', N'Bolivia', 0),
    (N'BQ', N'Caribbean Netherlands', 0),
    (N'BR', N'Brazil', 0),
    (N'BS', N'Bahamas', 0),
    (N'BT', N'Bhutan', 0),
    (N'BV', N'Bouvet Island', 0),
    (N'BW', N'Botswana', 0),
    (N'BY', N'Belarus', 0),
    (N'BZ', N'Belize', 0),
    (N'CA', N'Canada', 0),
    (N'CC', N'Cocos (Keeling) Islands', 0),
    (N'CD', N'Congo - Kinshasa', 0),
    (N'CF', N'Central African Republic', 0),
    (N'CG', N'Congo - Brazzaville', 0),
    (N'CH', N'Switzerland', 0),
    (N'CI', N'Côte d''Ivoire', 0),
    (N'CK', N'Cook Islands', 0),
    (N'CL', N'Chile', 0),
    (N'CM', N'Cameroon', 0),
    (N'CN', N'China', 0),
    (N'CO', N'Colombia', 0),
    (N'CP', N'Clipperton Island', 0),
    (N'CR', N'Costa Rica', 0),
    (N'CU', N'Cuba', 0),
    (N'CV', N'Cape Verde', 0),
    (N'CW', N'Curaçao', 0),
    (N'CX', N'Christmas Island', 0),
    (N'CY', N'Cyprus', 0),
    (N'CZ', N'Czech Republic', 0),
    (N'DE', N'Germany', 0),
    (N'DG', N'Diego Garcia', 0),
    (N'DJ', N'Djibouti', 0),
    (N'DK', N'Denmark', 0),
    (N'DM', N'Dominica', 0),
    (N'DO', N'Dominican Republic', 0),
    (N'DZ', N'Algeria', 0),
    (N'EA', N'Ceuta & Melilla', 0),
    (N'EC', N'Ecuador', 0),
    (N'EE', N'Estonia', 0),
    (N'EG', N'Egypt', 0),
    (N'EH', N'Western Sahara', 0),
    (N'ER', N'Eritrea', 0),
    (N'ES', N'Spain', 0),
    (N'ET', N'Ethiopia', 0),
    (N'FI', N'Finland', 0),
    (N'FJ', N'Fiji', 0),
    (N'FK', N'Falkland Islands', 0),
    (N'FM', N'Micronesia', 0),
    (N'FO', N'Faroe Islands', 0),
    (N'FR', N'France', 0),
    (N'GA', N'Gabon', 0),
    (N'GB', N'United Kingdom', 0),
    (N'GD', N'Grenada', 0),
    (N'GE', N'Georgia', 0),
    (N'GF', N'French Guiana', 0),
    (N'GG', N'Guernsey', 0),
    (N'GH', N'Ghana', 0),
    (N'GI', N'Gibraltar', 0),
    (N'GL', N'Greenland', 0),
    (N'GM', N'Gambia', 0),
    (N'GN', N'Guinea', 0),
    (N'GP', N'Guadeloupe', 0),
    (N'GQ', N'Equatorial Guinea', 0),
    (N'GR', N'Greece', 0),
    (N'GS', N'South Georgia & South Sandwich Islands', 0),
    (N'GT', N'Guatemala', 0),
    (N'GU', N'Guam', 0),
    (N'GW', N'Guinea-Bissau', 0),
    (N'GY', N'Guyana', 0),
    (N'HK', N'Hong Kong', 0),
    (N'HM', N'Heard & McDonald Islands', 0),
    (N'HN', N'Honduras', 0),
    (N'HR', N'Croatia', 0),
    (N'HT', N'Haiti', 0),
    (N'HU', N'Hungary', 0),
    (N'IC', N'Canary Islands', 0),
    (N'ID', N'Indonesia', 0),
    (N'IE', N'Ireland', 0),
    (N'IL', N'Israel', 0),
    (N'IM', N'Isle of Man', 0),
    (N'IN', N'India', 0),
    (N'IO', N'British Indian Ocean Territory', 0),
    (N'IQ', N'Iraq', 0),
    (N'IR', N'Iran', 0),
    (N'IS', N'Iceland', 0),
    (N'IT', N'Italy', 0),
    (N'JE', N'Jersey', 0),
    (N'JM', N'Jamaica', 0),
    (N'JO', N'Jordan', 0),
    (N'JP', N'Japan', 0),
    (N'KE', N'Kenya', 0),
    (N'KG', N'Kyrgyzstan', 0),
    (N'KH', N'Cambodia', 0),
    (N'KI', N'Kiribati', 0),
    (N'KM', N'Comoros', 0),
    (N'KN', N'St. Kitts & Nevis', 0),
    (N'KP', N'North Korea', 0),
    (N'KR', N'South Korea', 0),
    (N'KW', N'Kuwait', 0),
    (N'KY', N'Cayman Islands', 0),
    (N'KZ', N'Kazakhstan', 0),
    (N'LA', N'Laos', 0),
    (N'LB', N'Lebanon', 0),
    (N'LC', N'St. Lucia', 0),
    (N'LI', N'Liechtenstein', 0),
    (N'LK', N'Sri Lanka', 0),
    (N'LR', N'Liberia', 0),
    (N'LS', N'Lesotho', 0),
    (N'LT', N'Lithuania', 0),
    (N'LU', N'Luxembourg', 0),
    (N'LV', N'Latvia', 0),
    (N'LY', N'Libya', 0),
    (N'MA', N'Morocco', 0),
    (N'MC', N'Monaco', 0),
    (N'MD', N'Moldova', 0),
    (N'ME', N'Montenegro', 0),
    (N'MF', N'St. Martin', 0),
    (N'MG', N'Madagascar', 0),
    (N'MH', N'Marshall Islands', 0),
    (N'MK', N'North Macedonia', 0),
    (N'ML', N'Mali', 0),
    (N'MM', N'Myanmar (Burma)', 0),
    (N'MN', N'Mongolia', 0),
    (N'MO', N'Macau', 0),
    (N'MP', N'Northern Mariana Islands', 0),
    (N'MQ', N'Martinique', 0),
    (N'MR', N'Mauritania', 0),
    (N'MS', N'Montserrat', 0),
    (N'MT', N'Malta', 0),
    (N'MU', N'Mauritius', 0),
    (N'MV', N'Maldives', 0),
    (N'MW', N'Malawi', 0),
    (N'MX', N'Mexico', 0),
    (N'MY', N'Malaysia', 0),
    (N'MZ', N'Mozambique', 0),
    (N'NA', N'Namibia', 0),
    (N'NC', N'New Caledonia', 0),
    (N'NE', N'Niger', 0),
    (N'NF', N'Norfolk Island', 0),
    (N'NG', N'Nigeria', 0),
    (N'NI', N'Nicaragua', 0),
    (N'NL', N'Netherlands', 0),
    (N'NO', N'Norway', 0),
    (N'NP', N'Nepal', 0),
    (N'NR', N'Nauru', 0),
    (N'NU', N'Niue', 0),
    (N'NZ', N'New Zealand', 0),
    (N'OM', N'Oman', 0),
    (N'PA', N'Panama', 0),
    (N'PE', N'Peru', 0),
    (N'PF', N'French Polynesia', 0),
    (N'PG', N'Papua New Guinea', 0),
    (N'PH', N'Philippines', 0),
    (N'PK', N'Pakistan', 0),
    (N'PL', N'Poland', 0),
    (N'PM', N'St. Pierre & Miquelon', 0),
    (N'PN', N'Pitcairn Islands', 0),
    (N'PR', N'Puerto Rico', 0),
    (N'PS', N'Palestinian Territories', 0),
    (N'PT', N'Portugal', 0),
    (N'PW', N'Palau', 0),
    (N'PY', N'Paraguay', 0),
    (N'QA', N'Qatar', 0),
    (N'QO', N'Outlying Oceania', 0),
    (N'RE', N'Réunion', 0),
    (N'RO', N'Romania', 0),
    (N'RS', N'Serbia', 0),
    (N'RU', N'Russia', 0),
    (N'RW', N'Rwanda', 0),
    (N'SA', N'Saudi Arabia', 0),
    (N'SB', N'Solomon Islands', 0),
    (N'SC', N'Seychelles', 0),
    (N'SD', N'Sudan', 0),
    (N'SE', N'Sweden', 0),
    (N'SG', N'Singapore', 0),
    (N'SH', N'St. Helena', 0),
    (N'SI', N'Slovenia', 0),
    (N'SJ', N'Svalbard & Jan Mayen', 0),
    (N'SK', N'Slovakia', 0),
    (N'SL', N'Sierra Leone', 0),
    (N'SM', N'San Marino', 0),
    (N'SN', N'Senegal', 0),
    (N'SO', N'Somalia', 0),
    (N'SR', N'Suriname', 0),
    (N'SS', N'South Sudan', 0),
    (N'ST', N'São Tomé & Príncipe', 0),
    (N'SV', N'El Salvador', 0),
    (N'SX', N'Sint Maarten', 0),
    (N'SY', N'Syria', 0),
    (N'SZ', N'Eswatini', 0),
    (N'TA', N'Tristan da Cunha', 0),
    (N'TC', N'Turks & Caicos Islands', 0),
    (N'TD', N'Chad', 0),
    (N'TF', N'French Southern Territories', 0),
    (N'TG', N'Togo', 0),
    (N'TH', N'Thailand', 0),
    (N'TJ', N'Tajikistan', 0),
    (N'TK', N'Tokelau', 0),
    (N'TL', N'Timor-Leste', 0),
    (N'TM', N'Turkmenistan', 0),
    (N'TN', N'Tunisia', 0),
    (N'TO', N'Tonga', 0),
    (N'TR', N'Turkey', 0),
    (N'TT', N'Trinidad & Tobago', 0),
    (N'TV', N'Tuvalu', 0),
    (N'TW', N'Taiwan', 0),
    (N'TZ', N'Tanzania', 0),
    (N'UA', N'Ukraine', 0),
    (N'UG', N'Uganda', 0),
    (N'UM', N'U.S. Outlying Islands', 0),
    (N'US', N'United States', 0),
    (N'UY', N'Uruguay', 0),
    (N'UZ', N'Uzbekistan', 0),
    (N'VA', N'Vatican City', 0),
    (N'VC', N'St. Vincent & Grenadines', 0),
    (N'VE', N'Venezuela', 0),
    (N'VG', N'British Virgin Islands', 0),
    (N'VI', N'U.S. Virgin Islands', 0),
    (N'VN', N'Vietnam', 0),
    (N'VU', N'Vanuatu', 0),
    (N'WF', N'Wallis & Futuna', 0),
    (N'WS', N'Samoa', 0),
    (N'XK', N'Kosovo', 0),
    (N'YE', N'Yemen', 0),
    (N'YT', N'Mayotte', 0),
    (N'ZA', N'South Africa', 0),
    (N'ZM', N'Zambia', 0),
    (N'ZW', N'Zimbabwe', 0);