// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAndPricingNew.Persistence;

#nullable disable

namespace ProductsAndPricingNew.Persistence.Migrations
{
    [DbContext(typeof(ProductsAndPricingDbContext))]
    [Migration("20260511151927_CreateEditorTable")]
    partial class CreateEditorTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsAndPricingNew.Domain.Edit.Editor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Editor", "Edit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "noreply@ecenglish.com",
                            FirstName = "System",
                            LastName = "User",
                            UserName = "SYSTEM"
                        });
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.Entities.PricingRef.AccountCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.ComplexProperty<Dictionary<string, object>>("AuditMetadata", "ProductsAndPricingNew.Domain.Entities.PricingRef.AccountCategory.AuditMetadata#AuditMetadata", b1 =>
                        {
                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedAt");

                            b1.Property<int>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedAt");

                            b1.Property<int>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DivisionId", "Name");

                    b.HasIndex("DivisionId", "IsDeleted", "IsActive");

                    b.ToTable("AccountCategory", "Product");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.Entities.PricingRef.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupsPaymentTerms")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("HeadOfficeEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HeadOfficeTelephoneNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TermsAndConditions")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.ComplexProperty<Dictionary<string, object>>("AccreditationBanner", "ProductsAndPricingNew.Domain.Entities.PricingRef.Division.AccreditationBanner#ImageFile", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContentType")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BannerContentType");

                            b1.Property<byte[]>("Data")
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("BannerData");

                            b1.Property<string>("FileName")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("BannerFileName");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("AuditMetadata", "ProductsAndPricingNew.Domain.Entities.PricingRef.Division.AuditMetadata#AuditMetadata", b1 =>
                        {
                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedAt");

                            b1.Property<int>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedAt");

                            b1.Property<int>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ContactAddress", "ProductsAndPricingNew.Domain.Entities.PricingRef.Division.ContactAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("City");

                            b1.Property<int?>("CountryId")
                                .HasColumnType("int")
                                .HasColumnName("CountryId");

                            b1.Property<string>("District")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("District");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Street");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Division", "PricingRef");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.Entities.PricingRef.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.ComplexProperty<Dictionary<string, object>>("AuditMetadata", "ProductsAndPricingNew.Domain.Entities.PricingRef.ProductCategory.AuditMetadata#AuditMetadata", b1 =>
                        {
                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedAt");

                            b1.Property<int>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedAt");

                            b1.Property<int>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DivisionId", "Name");

                    b.HasIndex("DivisionId", "IsDeleted", "IsActive");

                    b.ToTable("ProductCategory", "Product");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.Entities.Products.AddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("AddOnTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("OfferingsClosureDate")
                        .HasColumnType("date");

                    b.Property<int?>("OneToOneLessonsPerWeek")
                        .HasColumnType("int")
                        .HasColumnName("OneToOneLessonsPerWeek");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.ComplexProperty<Dictionary<string, object>>("AuditMetadata", "ProductsAndPricingNew.Domain.Entities.Products.AddOn.AuditMetadata#AuditMetadata", b1 =>
                        {
                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedAt");

                            b1.Property<int>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedAt");

                            b1.Property<int>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("FinanceCodes", "ProductsAndPricingNew.Domain.Entities.Products.AddOn.FinanceCodes#FinanceCodes", b1 =>
                        {
                            b1.Property<string>("CostCentreCode")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CostCentreCode");

                            b1.Property<string>("GeneralLedgerCode")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("GeneralLedgerCode");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AccountCategoryId");

                    b.HasIndex("AddOnTypeId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("DivisionId", "Name");

                    b.ToTable("AddOn", "Product");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.Entities.Products.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CourseIntensityId")
                        .HasColumnType("int");

                    b.Property<int>("CourseLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumWeeks")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("OfferingsClosureDate")
                        .HasColumnType("date");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.ComplexProperty<Dictionary<string, object>>("AuditMetadata", "ProductsAndPricingNew.Domain.Entities.Products.Course.AuditMetadata#AuditMetadata", b1 =>
                        {
                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedAt");

                            b1.Property<int>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedAt");

                            b1.Property<int>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("FinanceCodes", "ProductsAndPricingNew.Domain.Entities.Products.Course.FinanceCodes#FinanceCodes", b1 =>
                        {
                            b1.Property<string>("CostCentreCode")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CostCentreCode");

                            b1.Property<string>("GeneralLedgerCode")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("GeneralLedgerCode");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DivisionId", "Name");

                    b.ToTable("Course", "Product");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.Entities.Products.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaximumAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumWeeks")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("OfferingsClosureDate")
                        .HasColumnType("date");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.ComplexProperty<Dictionary<string, object>>("AuditMetadata", "ProductsAndPricingNew.Domain.Entities.Products.Package.AuditMetadata#AuditMetadata", b1 =>
                        {
                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedAt");

                            b1.Property<int>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedAt");

                            b1.Property<int>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("FinanceCodes", "ProductsAndPricingNew.Domain.Entities.Products.Package.FinanceCodes#FinanceCodes", b1 =>
                        {
                            b1.Property<string>("CostCentreCode")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CostCentreCode");

                            b1.Property<string>("GeneralLedgerCode")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("GeneralLedgerCode");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AccountCategoryId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("DivisionId", "Name");

                    b.ToTable("Package", "Product");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.Entities.Products.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("OfferingsClosureDate")
                        .HasColumnType("date");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("TimeFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("TimeTo")
                        .HasColumnType("time");

                    b.Property<int>("TransferPortId")
                        .HasColumnType("int");

                    b.Property<int>("TransferTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.ComplexProperty<Dictionary<string, object>>("AuditMetadata", "ProductsAndPricingNew.Domain.Entities.Products.Transfer.AuditMetadata#AuditMetadata", b1 =>
                        {
                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedAt");

                            b1.Property<int>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedAt");

                            b1.Property<int>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("FinanceCodes", "ProductsAndPricingNew.Domain.Entities.Products.Transfer.FinanceCodes#FinanceCodes", b1 =>
                        {
                            b1.Property<string>("CostCentreCode")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CostCentreCode");

                            b1.Property<string>("GeneralLedgerCode")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("GeneralLedgerCode");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AccountCategoryId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("TransferPortId");

                    b.HasIndex("TransferTypeId");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("DivisionId", "Name");

                    b.ToTable("Transfer", "Product");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.Entities.Products.TransferPort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TransferPortTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.ComplexProperty<Dictionary<string, object>>("AuditMetadata", "ProductsAndPricingNew.Domain.Entities.Products.TransferPort.AuditMetadata#AuditMetadata", b1 =>
                        {
                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CreatedAt");

                            b1.Property<int>("CreatedById")
                                .HasColumnType("int")
                                .HasColumnName("CreatedById");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("UpdatedAt");

                            b1.Property<int>("UpdatedById")
                                .HasColumnType("int")
                                .HasColumnName("UpdatedById");
                        });

                    b.HasKey("Id");

                    b.ToTable("TransferPort", "Product");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.ReferenceData.Audience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Audience", "ReferenceData");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.ReferenceData.ContentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<short>("Scope")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("ContentTemplate", "ReferenceData");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.ReferenceData.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Country", "ReferenceData");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.ReferenceData.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Currency", "ReferenceData");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.ReferenceData.DivisionTextContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AudienceId")
                        .HasColumnType("int");

                    b.Property<int>("ContentTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.ComplexProperty<Dictionary<string, object>>("Text", "ProductsAndPricingNew.Domain.ReferenceData.DivisionTextContent.Text#FormattedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(10000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Content");

                            b1.Property<short>("Format")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("smallint")
                                .HasDefaultValue((short)0)
                                .HasColumnName("Format");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AudienceId");

                    b.HasIndex("ContentTemplateId");

                    b.HasIndex("DivisionId", "ContentTemplateId", "AudienceId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("DivisionTextContent", "PricingRef");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.Entities.Products.Package", b =>
                {
                    b.OwnsMany("ProductsAndPricingNew.Domain.Entities.Products.PackageItem", "Items", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("PackageId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Percentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("Percentage");

                            b1.Property<int>("ProductDefinitionId")
                                .HasColumnType("int")
                                .HasColumnName("ProductDefinitionId");

                            b1.Property<int>("ProductKind")
                                .HasColumnType("int")
                                .HasColumnName("ProductKind");

                            b1.HasKey("Id");

                            b1.HasIndex("PackageId", "ProductKind", "ProductDefinitionId")
                                .IsUnique();

                            b1.ToTable("PackageItem", "Product");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.Entities.Products.TransferPort", b =>
                {
                    b.OwnsMany("ProductsAndPricingNew.Domain.Entities.Products.TransferPortInstruction", "Instructions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DivisionId")
                                .HasColumnType("int");

                            b1.Property<string>("Instructions")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<int>("TransferPortId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("TransferPortId", "DivisionId")
                                .IsUnique();

                            b1.ToTable("TransferPortInstruction", "Product");

                            b1.WithOwner()
                                .HasForeignKey("TransferPortId");
                        });

                    b.OwnsMany("ProductsAndPricingNew.Domain.Entities.Products.TransferPortTerminal", "Terminals", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<int>("Number")
                                .HasColumnType("int");

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<int>("TransferPortId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("TransferPortId", "Number")
                                .IsUnique();

                            b1.ToTable("TransferPortTerminal", "Product");

                            b1.WithOwner()
                                .HasForeignKey("TransferPortId");
                        });

                    b.Navigation("Instructions");

                    b.Navigation("Terminals");
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.ReferenceData.DivisionTextContent", b =>
                {
                    b.HasOne("ProductsAndPricingNew.Domain.ReferenceData.Audience", null)
                        .WithMany()
                        .HasForeignKey("AudienceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProductsAndPricingNew.Domain.ReferenceData.ContentTemplate", null)
                        .WithMany()
                        .HasForeignKey("ContentTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductsAndPricingNew.Domain.Entities.PricingRef.Division", null)
                        .WithMany("Texts")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductsAndPricingNew.Domain.Entities.PricingRef.Division", b =>
                {
                    b.Navigation("Texts");
                });
#pragma warning restore 612, 618
        }
    }
}
